### ISSUE TITLE
Get some rest son

### ISSUE THREAD

**Issue by sperglord8008s** [js32-us/AceSeed1#1]

**Comment by js32-us** [comment]
Rest would be great, but bills and taxes know no such thing.. lol trying to learn a ton at once is tiring that’s for sure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: sperglord8008s ***@***.***>
Sent: Friday, April 1, 2022 9:08:38 AM
To: js32-us/AceSeed1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [js32-us/AceSeed1] Get some rest son (Issue #1)
